---
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: github-actions"
      include: "scope"
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: devcontainers"
      include: "scope"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: docker"
      include: "scope"
  - package-ecosystem: "docker-compose"
    directory: "/tests"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: docker-compose"
      include: "scope"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: terraform"
      include: "scope"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: ":dependabot: uv"
      include: "scope"
