---
name: 🦝 Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@e0b96059804cbe750acb4a495ec6106617972f0b # v4.1.0
    with:
      super-linter-variables: |
        {
          "VALIDATE_TERRAFORM_TERRASCAN": false
        }
