---
name: 🦝 Super Linter

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  super-linter:
    name: Super Linter
    permissions:
      contents: read
      packages: read
      statuses: write
    uses: ministryofjustice/analytical-platform-github-actions/.github/workflows/reusable-super-linter.yml@31245f6d7852ff4fbb735ec759cf42d182f5836e # v5.0.0
    with:
      super-linter-variables: |
        {
          "VALIDATE_TERRAFORM_TERRASCAN": false
        }
